instance_groups:
- name: elasticsearch_master
  instances: 1
  vm_type: t3.medium
  networks:
  - name: services
    static_ips:
    - (( replace ))
    - (( grab terraform_outputs.logsearch_static_ips.[7]))

- name: maintenance
  vm_type: t3.medium
  jobs:
  - name: curator
    properties:
      curator:
        purge_logs:
          retention_period: 7

- name: kibana
  vm_type: t3.large
  instances: 1
  jobs:
  - name: oauth2-proxy
    properties:
      redirect_url: https://logs-platform.dev.us-gov-west-1.aws-us-gov.cloud.gov/oauth2/callback

- name: ingestor
  instances: 1
  vm_type: t3.medium

- name: elasticsearch_data
  instances: 3
  vm_type: t3.medium

- name: smoke-tests
  vm_type: t3.small
  jobs:
  - name: smoke_tests
    properties:
      smoke_tests:
        count_test:
          run: true
          minimum: 10000
          time_interval: "5m"
          time_field: "@timestamp"
          index_pattern: "logs-platform-*"

stemcells:
- alias: default
  name: bosh-aws-xen-hvm-ubuntu-bionic-go_agent
  version: latest
