instance_groups:
- name: elasticsearch_master
  vm_type: t3.xlarge

- name: maintenance
  vm_type: t3.large

- name: kibana
  vm_type: t3.xlarge
  jobs:
  - name: oauth2-proxy
    properties:
      redirect_url: https://logs-platform.fr.cloud.gov/oauth2/callback

- name: ingestor
  vm_type: r5.xlarge.logsearch.ingestor
  jobs:
  - name: ingestor_syslog
    properties:
      logstash_ingestor:
        health:
          timeout: 900

- name: elasticsearch_data
  vm_type: r5.xlarge
  update:
    max_in_flight: 2
    canaries: 2

- name: redis
  instances: 1
  vm_type: t3.medium

- name: smoke-tests
  vm_type: t3.small
  jobs:
  - name: smoke_tests
    properties:
      smoke_tests:
        count_test:
          run: true
          minimum: 50000
          time_interval: "5m"
          time_field: "@timestamp"
          index_pattern: "logs-platform-*"

stemcells:
- alias: default
  name: bosh-aws-xen-hvm-ubuntu-bionic-go_agent
  version: latest
